# Site settings
title: Dev Talk
description: Front-End Web Talk
keywords: tweenout, Todd Shelton, Dev Workshop
author: Todd Shelton
baseurl: "/tweenout-blog" # the subpath of your site, e.g. /blog/
url: "https://tshelton41.github.io" # the base hostname & protocol for your site
